name: deno

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.6.1
      - name: check format
        run: deno fmt --check
      - name: check lint
        run: deno lint --unstable
